services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: bookmyhome-mssql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=6!8GSPTuHGHsmFfwrH!
      - MSSQL_PID=Developer
    ports:
      - "5000:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  BookMyHome-UserService:
    depends_on:
      - mssql
    image: ghcr.io/hiha76740/bookmyhome-userservice:latest
    container_name: bookmyhome-userservice
    restart: unless-stopped
    ports:
        - 9000:8080
        - 9010:8081
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro

    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s


  BookMyHome-BookingService:
    depends_on:
      - mssql
    image: ghcr.io/hiha76740/bookmyhome-bookingservice:latest
    container_name: bookmyhome-bookingservice
    restart: unless-stopped
    ports:
        - 9001:8080
        - 9011:8081
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro
        
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s


  BookMyHome-AccomodationService:
    depends_on:
      - mssql
    image: ghcr.io/hiha76740/bookmyhome-accomodationservice:latest
    container_name: bookmyhome-accomodationservice
    restart: unless-stopped
    ports:
        - 9002:8080
        - 9012:8081
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro

    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s



  watchtower:
    image: nickfedor/watchtower
    container_name: bookmyhome-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: "true"
    command: --label-enable
        

volumes:
    mssql-data: