services:

  BookMyHome-Proxy:
    image: ghcr.io/hiha76740/bookmyhome-proxy:latest
    container_name: bookmyhome-proxy
    restart: unless-stopped
    ports:
        - 8000:8080
        - 8010:8081
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro
        
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
  
 
 
  mssql-UserDB:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql-userdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=6!8GSPTuHGHsmFfwrH!
      - MSSQL_PID=Developer
    volumes:
      - mssql-userdb-data:/var/opt/mssql
    restart: unless-stopped
 
  BookMyHome-UserService1:
    depends_on:
      - mssql-UserDB
    image: ghcr.io/hiha76740/bookmyhome-userservice:latest
    container_name: bookmyhome-userservice1
    restart: unless-stopped
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro

    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
      
  BookMyHome-UserService2:
    depends_on:
      - mssql-UserDB
    image: ghcr.io/hiha76740/bookmyhome-userservice:latest
    container_name: bookmyhome-userservice2
    restart: unless-stopped
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro

    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
  
  
  mssql-BookingDB:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql-bookingdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=6!8GSPTuHGHsmFfwrH!
      - MSSQL_PID=Developer
    volumes:
      - mssql-bookingdb-data:/var/opt/mssql
    restart: unless-stopped

  BookMyHome-BookingService1:
    depends_on:
      - mssql-BookingDB
    image: ghcr.io/hiha76740/bookmyhome-bookingservice:latest
    container_name: bookmyhome-bookingservice1
    restart: unless-stopped
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro
        
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s


  BookMyHome-BookingService2:
    depends_on:
      - mssql-BookingDB
    image: ghcr.io/hiha76740/bookmyhome-bookingservice:latest
    container_name: bookmyhome-bookingservice2
    restart: unless-stopped
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro
        
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s


  mssql-AccomodationDB:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: mssql-accomodationdb
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=6!8GSPTuHGHsmFfwrH!
      - MSSQL_PID=Developer
    volumes:
      - mssql-Accomodationdb-data:/var/opt/mssql
    restart: unless-stopped


  BookMyHome-AccomodationService1:
    depends_on:
      - mssql-AccomodationDB
    image: ghcr.io/hiha76740/bookmyhome-accomodationservice:latest
    container_name: bookmyhome-accomodationservice1
    restart: unless-stopped
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro
        - BookMyHome-Images:/app/Storage/images

    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
      
  BookMyHome-AccomodationService2:
    depends_on:
      - mssql-AccomodationDB
    image: ghcr.io/hiha76740/bookmyhome-accomodationservice:latest
    container_name: bookmyhome-accomodationservice2
    restart: unless-stopped
        
    environment:
        ASPNETCORE_URLS: "http://+:8080;https://+:8081"
        
        ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/bookmyhome.pfx"
        ASPNETCORE_Kestrel__Certificates__Default__Password: "DinDevelopmentKode123"

    volumes:
        - ${USERPROFILE}/.aspnet/https:/https:ro
        - BookMyHome-Images:/app/Storage/images

    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s


  watchtower:
    image: nickfedor/watchtower
    container_name: bookmyhome-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: "true"
    command: --label-enable
        

volumes:
    mssql-userdb-data:
    mssql-bookingdb-data:
    mssql-Accomodationdb-data:
    BookMyHome-Images: