services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: bookmyhome-mssql-server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=6*8GSPTuHGHsmF$fwrH$
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped

  BookMyHome-BookingService:
    depends_on:
      - mssql
    image: ghcr.io/hiha76740/bookmyhome-bookingservice:latest
    container_name: bookmyhome-bookingservice
    restart: unless-stopped
    ports:
        - 8080:8080

    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s

  watchtower:
    image: nickfedor/watchtower
    container_name: bookmyhome-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: 30
      WATCHTOWER_CLEANUP: "true"
    command: --label-enable
        

volumes:
  mssql-data: