// <auto-generated />
using System;
using System.Collections.Generic;
using AccomodationService.InfrastructureLib.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccomodationService.InfrastructureLib.Migrations
{
    [DbContext(typeof(AccomodationDbContext))]
    [Migration("20261007102604_Intial")]
    partial class Intial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccomodationFacility", b =>
                {
                    b.Property<Guid>("AccomodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("facilitiesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccomodationId", "facilitiesId");

                    b.HasIndex("facilitiesId");

                    b.ToTable("AccommodationFacilities", (string)null);
                });

            modelBuilder.Entity("AccomodationService.DomainLib.Entities.Accomodation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "AccomodationService.DomainLib.Entities.Accomodation.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired();

                            b1.Property<string>("Country")
                                .IsRequired();

                            b1.Property<string>("PostalCode")
                                .IsRequired();

                            b1.Property<string>("Street")
                                .IsRequired();

                            b1
                                .ToJson("Address")
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.ToTable("Accomodations");
                });

            modelBuilder.Entity("AccomodationService.DomainLib.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Facilities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("68a14b26-15d6-4831-a876-221b01260c6b"),
                            Name = "Wifi"
                        },
                        new
                        {
                            Id = new Guid("389ee76d-5478-43a4-a5f9-94a9f8133eb9"),
                            Name = "Pool"
                        },
                        new
                        {
                            Id = new Guid("ab46c03f-4440-4ef9-8137-9dc09f82b94c"),
                            Name = "Air Conditioning"
                        },
                        new
                        {
                            Id = new Guid("1eff118c-87f2-45f6-8f1e-2a4ce1f1ccff"),
                            Name = "Opvaskemaskine"
                        },
                        new
                        {
                            Id = new Guid("f595c2a6-13b0-438c-bc63-c08fff41ddc4"),
                            Name = "Gym"
                        },
                        new
                        {
                            Id = new Guid("1d4d28b2-edc2-4aaa-be9e-e855f4dd7cd3"),
                            Name = "Grill"
                        },
                        new
                        {
                            Id = new Guid("0fb02b10-29ea-4616-83d8-5e7870e24c3f"),
                            Name = "Hot Tub"
                        },
                        new
                        {
                            Id = new Guid("420dedfe-0bed-40ab-b036-63fbe52fbbab"),
                            Name = "EV Lader"
                        },
                        new
                        {
                            Id = new Guid("35ae0b5a-36cf-4242-a7f3-f10a616e6626"),
                            Name = "TV"
                        },
                        new
                        {
                            Id = new Guid("a5d70bf0-67d1-4a14-bf0b-2857d3307e11"),
                            Name = "Vaskemaskine"
                        },
                        new
                        {
                            Id = new Guid("6f95b1bd-1039-493b-b681-b1da44d949f8"),
                            Name = "Tørretumbler"
                        });
                });

            modelBuilder.Entity("AccomodationService.DomainLib.Entities.Listing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccomodationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HouseRules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccomodationId");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("AccomodationFacility", b =>
                {
                    b.HasOne("AccomodationService.DomainLib.Entities.Accomodation", null)
                        .WithMany()
                        .HasForeignKey("AccomodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AccomodationService.DomainLib.Entities.Facility", null)
                        .WithMany()
                        .HasForeignKey("facilitiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AccomodationService.DomainLib.Entities.Listing", b =>
                {
                    b.HasOne("AccomodationService.DomainLib.Entities.Accomodation", "Accomodation")
                        .WithMany("listings")
                        .HasForeignKey("AccomodationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accomodation");
                });

            modelBuilder.Entity("AccomodationService.DomainLib.Entities.Accomodation", b =>
                {
                    b.Navigation("listings");
                });
#pragma warning restore 612, 618
        }
    }
}
