<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BookMyHome.DomainLib\BookMyHome.DomainLib.csproj" />
    <ProjectReference Include="..\BookMyHome.FacadeLib\BookMyHome.FacadeLib.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
