name: BookingService CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "BookMyHome/src/BookingService/**"

permissions:
  contents: read

env:
  DOTNET_VERSION: "10.0.x"
  SOLUTION_PATH: "BookMyHome/BookMyHome.slnx"
  DOMAIN_PROJECT_PATH: "BookMyHome/tests/BookingService/BookingService.DomainLib.Tests/BookingService.DomainLib.Tests.csproj"
  APPLICATION_PROJECT_PATH: "BookMyHome/tests/BookingService/BookingService.ApplicationLib.Tests/BookingService.ApplicationLib.Tests.csproj"

jobs:
  Build-And-Test-Domain:
    name: Build and Test Domain
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }}
          --configuration Release
          --no-restore

      - name: Test Domain
        run: dotnet test --project ${{ env.DOMAIN_PROJECT_PATH }}
          --configuration Release
          --no-restore
          --no-build
          --verbosity normal


  Build-And-Test-Application:
    needs: Build-And-Test-Domain
    name: Build and Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore
        run: dotnet restore ${{ env.SOLUTION_PATH }}

      - name: Build
        run: dotnet build ${{ env.SOLUTION_PATH }}
          --configuration Release
          --no-restore

      - name: Test Application
        run: dotnet test --project ${{ env.APPLICATION_PROJECT_PATH }}
          --configuration Release
          --no-restore
          --no-build
          --verbosity normal